# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0030_auto_20170702_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='city',
        ),
    ]
