# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meupet', '0032_auto_20171219_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='group_photos')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meupet.Group')),
            ],
        ),
    ]
